### ISSUE TITLE
Update "Standard Cluster" yaml in Documentation to reflect "Config" yaml variables

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/k2#115]
To spin up a K2 cluster you need a config yaml. Currently this yaml contains the necessary variables to successfully spin up a cluster:
https://github.com/samsung-cnct/k2/blob/master/ansible/roles/kraken.config/files/config.yaml

There is another config yaml in the Documentation/samples directory that is out of date:
https://github.com/samsung-cnct/k2/blob/master/Documentation/samples/standard_cluster.yaml

Update Documentation or remove redundancy by redirecting to config.yaml.

**Comment by davidewatson** [comment]
Sadly, Markdown does not natively support include directives, though links are possible (https://github.com/blog/1395-relative-links-in-markup-files).

The samples directory isn't referenced anywhere as far as I can tell. Methinks this makes it fair game to delete. On the other hand, our default configuration is fairly large (instance-wise) due to HA requirements. In the future we might want to add alternative samples. But if we did that, then we would have to explain them, which is a larger, but worthy, documentation effort.

Therefore I vote we delete the samples directory for now.

**Comment by leahnp** [comment]
I also vote for deleting the sample directory.

**Comment by coffeepac** [comment]
I like the idea of a sample directory as this is a very complicated tool.  But this probably isn't the best long term home for it anyway (should be either [public github page](http://samsung-cnct.github.io/) or k2cli) so nuking the whole directory is probably a good idea.

**Comment by leahnp** [comment]
Resolved with: https://github.com/samsung-cnct/k2/pull/215
