### ISSUE TITLE
Manual Joyent K8s blog post

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#147]
write a blog post on how to install k8s on JPC manually.  bonus points if the terraform configs work but bonus points are not required.

**Comment by joejulian** [comment]
WIP https://github.com/joejulian/kubernetes-the-hard-way/tree/joyent

**Comment by joejulian** [comment]
Joyent's docker api does not implement any networking features. By setting network-plugin to an empty string, the pod container can start but since https://github.com/kubernetes/kubernetes/commit/244152544ce#diff-e2eefa11d78ba95197ce406772c18c30R2317 there is no way to prevent a network from being passed for the actual run container.

I've got a ticket open with Joyent regarding the errors that occur with their docker api: https://help.joyent.com/hc/en-us/requests/203494
I've opened a feature request with kubernetes: https://github.com/kubernetes/kubernetes/issues/40238

**Comment by joejulian** [comment]
Posted awaiting review: https://joejulian.name/blog/kubernetes-on-joyent-the-hard-way-part-1-infrastructure/

**Comment by coffeepac** [comment]
this has been sent to joyent for review.  off to review it goes.

**Comment by coffeepac** [comment]
currently in-review process.  new repo created for collaborating.  I'm going to close this ticket as we will handle the rest of this over there.  should be light touch on our end.  if it isn't I'll reopen this so we can keep track.
