### ISSUE TITLE
Identify Admin/Special nodes through taints

### ISSUE THREAD

**Issue by venezia** [samsung-cnct/k2#151]
Instead of specifying custom node labels for special nodes, we should apply taints to any node that is not "normal".  This can be for the control plane nodes (if we want to do that) or for _special_ nodes.

Starting with K8S 1.6, taints can be registered with kubelet, thus offering easy integration with cloud init scripts

**Comment by davidewatson** [comment]
I am looking at this right now as an example of how to extend k2 configurations under the k2recon project (#221, #222).

Some notes on taints and tolerances: [design](https://github.com/glevand/kubernetes--kubernetes/blob/master/docs/design/taint-toleration-dedicated.md), [example](https://medium.com/@alejandro.ramirez.ch/reserving-a-kubernetes-node-for-specific-nodes-e75dc8297076#.8f7xgphem), and [current unschedulable} implementation](https://github.com/samsung-cnct/k2/blob/493f47c02d9cef50d18284e51a2ad679ad5699e2/ansible/roles/kraken.master/kraken.master.docker/templates/units.kubelet.part.jinja2#L41).

Some observations:

 - Currently schedulable=false is set implicitly when a node is a "master" node. This should be changed so that a taint is explicitly set within the configuration file.
 - Node labels (#60) should be implemented in an analogous way (i.e. explicitly set in the configuration file).

**Comment by coffeepac** [comment]
blocked by 1.6

**Comment by coffeepac** [comment]
duplicate
