### ISSUE TITLE
GKE node version change

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#217]
what is the manual process for rolling forward or rolling backwards the version of kubernetes running on a gke node?

this ticket should produce a set of command line steps to effect both up and down version changes.

Should also include about how long the process takes.

**Comment by DStorck** [comment]
https://cloud.google.com/container-engine/docs/clusters/upgrade

**Comment by DStorck** [comment]
from above page: 
Rolling back a node upgrade (ALPHA)

Container Engine now supports rolling back of Failed or Canceled node upgrades. If you roll back an upgrade, any nodes that have been upgraded will be rolled back to the previous configuration. Any nodes that had not been upgraded will be left as-is. However, note that you cannot roll back an upgrade that had previously completed successfully; a rollback operation on a successful upgrade is interpreted as a no-op.

You can roll back an upgrade by running the following command in your shell or terminal window:

gcloud alpha container node-pools rollback $POOL_NAME --cluster $CLUSTER_NAME

**Comment by coffeepac** [comment]
word choice issue on my part.  in the google cloud vernacular this ticket is about upgrades and downgrades of the cluster nodes.

**Comment by DStorck** [comment]
from the same page: 
Because the cluster master is managed by Google, the version of Kubernetes that is running on the master is automatically updated to the most recently released version. The cluster nodes, however, are not automatically upgraded when newer versions of the Kubernetes API are released. This allows you to upgrade on your own schedule, coordinating with other maintenance and avoiding impact during business-critical windows.

**Comment by DStorck** [comment]
Because the cluster master is managed by Google, the version of Kubernetes that is running on the master is automatically updated to the most recently released version. The cluster nodes, however, are not automatically upgraded when newer versions of the Kubernetes API are released. This allows you to upgrade on your own schedule, coordinating with other maintenance and avoiding impact during business-critical windows.

To find the supported master and node versions for upgrades, run the following command:

`gcloud container get-server-config [--zone=ZONE]`

To change your cluster nodes' version, use the gcloud container clusters upgrade command:

`gcloud container clusters upgrade $CLUSTER_NAME --cluster-version=$CLUSTER_VERSION`

- `CLUSTER_NAME` is the name of the container cluster to upgrade.
- `CLUSTER_VERSION` has the form X.Y.Z
- Optionally,` --cluster-version` can be used to upgrade or downgrade to a specific release. Omitting this flag upgrades the container cluster to the version on the master. If used, you must specify a version within two minor releases of the master's version, at the highest patch number. Supported versions are listed in the Release Notes.

When you initiate a cluster version change, each instance in the cluster is deleted one at a time. After the instance is deleted, Container Engine adds a new instance to the cluster with the specified Kubernetes API, as well as the associated base image, Docker daemon, kubelet, and kube-proxy.

I started a 3 node cluster and added the [cnct/central-logging system](https://github.com/samsung-cnct/k2-charts/tree/master/central-logging) for testing purposes.  It took 11 minutes to upgrade the cluster. 

More detailed info found at [Updating a Container Cluster](https://cloud.google.com/container-engine/docs/clusters/upgrade)

**Comment by DStorck** [comment]
From [Updating a Container Cluster](https://cloud.google.com/container-engine/docs/clusters/upgrade)

###Important considerations

Before beginning an upgrade or downgrade, there are some important details to consider.

- An upgrade/downgrade works by deleting all node instances, one at a time, and replacing them with new instances running the desired Kubernetes version.

- Before an instance is deleted, it is marked unschedulable and drained. Any pods running on the instance are deleted. If they are managed by a controller, the controller will attempt to reschedule the pods on the remaining instances. Pods that are not managed by a controller will not be restarted.  Once the node re-enters the fleet at the new version, it is marked schedulable.

- Any data in hostDir or emptyDir volumes in pods is deleted during an upgrade/downgrade. To preserve data across upgrade/downgrade, use a pod with a gcePersistentDisk volume. Note that this is different than the persistent disk created by default as a boot disk with Compute Engine instances; boot disks are deleted along with the instances as part of the upgrade/downgrade. A gcePersistentDisk volume is a disk created separately from your instances.

- When a node instance is shut down as part of an upgrade/downgrade, its replacement will be assigned the same instance name.

- Downgrades are supported up to two minor versions before the master's version (x.X.x), each at their latest patch version (x.x.X).

- You can find the supported master and node versions for upgrades by running the following command:

`gcloud container get-server-config [--zone=ZONE]`

**Comment by DStorck** [comment]
34 pods running on 5 nodes took : 
```
$ time  gcloud container clusters upgrade ds-more-pods --cluster-version=1.5.2 --zone=us-west1-a
All 5 nodes of cluster [ds-more-pods] will be upgraded from version
[1.5.3] to version [1.5.2]. This operation is long-running and will
block other operations on the cluster (including delete) until it has
run to completion.

Do you want to continue (Y/n)?  Y

Upgrading ds-more-pods... RollingUpdate finished in "us-west1-a"....done.
Updated [https://container.googleapis.com/v1/projects/k8s-work/zones/us-west1-a/clusters/ds-more-pods].

real	18m11.993s
user	0m1.282s
sys	0m0.232s
```

**Comment by DStorck** [comment]
11 pods running on 3 nodes: 
```
time gcloud container clusters upgrade ds-small-cluster --cluster-version=1.5.2
All 3 nodes of cluster [ds-small-cluster] will be upgraded from
version [1.5.3] to version [1.5.2]. This operation is long-running and
 will block other operations on the cluster (including delete) until
it has run to completion.

Do you want to continue (Y/n)?  Y

Upgrading ds-small-cluster... RollingUpdate finished in "us-central1-a"....done.
Updated [https://container.googleapis.com/v1/projects/k8s-work/zones/us-central1-a/clusters/ds-small-cluster].

real	12m14.141s
user	0m0.973s
sys	0m0.177s
```

**Comment by coffeepac** [comment]
ToReview:
- ensure that steps listed here: https://github.com/samsung-cnct/k2/issues/217#issuecomment-285467380 fully cover what we're up to
