### ISSUE TITLE
Migrate kubeConfig stanza

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#271]
# kubeConfig stanza

This ticket is to remove the old stanza, ```"#/deployment/kubeConfig”```, from ansible/roles/kraken.config/files/config.yaml  and update the dependent Ansible tasks to access ```#/deployment/clusters/{{clusterIndex}}/nodes/{{nodeIndex}}/kubeConfig```. instead. When doing this the k2 schema, ansible/roles/kraken.config/files/schema.json , should be updated as well.

**Comment by davidewatson** [comment]
Blocked on #276.

**Comment by guineveresaenger** [comment]
So it appears as though most of the work on this has already been done, as no doubt it conflicted with some other tasks.
The remainder of the work is in the gkr provider tasks, which the revised config file from #266 does not really support.

**Comment by guineveresaenger** [comment]
Also running into conflicts with #273

**Comment by guineveresaenger** [comment]
It looks like a lot of the migration work for gke has been done in https://github.com/samsung-cnct/k2/pull/332 by @coffeepac. 
All that remained to do was change the k8s minor version fact to reflect the new config file.  
We still will need to change references for the gke version of setting this fact, because that change is not reflected on the k2recon branch yet (it branched before gke minor version fact was merged).

Here's a PR: https://github.com/samsung-cnct/k2/pull/336

**Comment by guineveresaenger** [comment]
Can we close this ticket? The remaining work is being handled in #345 and #337 in a slightly different way.

**Comment by coffeepac** [comment]
yep.  out it goes.
