### ISSUE TITLE
add cluster version to gke clusters

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#299]
this page:  https://cloud.google.com/container-engine/release-notes makes it clear that we can specify what version to use to create a cluster.

this example:

`gcloud container  clusters create --cluster-version=1.4.9 zazzle --zone us-central1-c
Creating cluster zazzle...`

shows how it would work.  We need to do this to support version pinning and version changes of kubernetes.

This issue covers (or needs to have a follow-on issue created):
- adding a config option for gke clusters
- adding the version peg to the GKE PR job in kraken-ci-jobs
- setting kubernetes_minor_version for GKE

**Comment by guineveresaenger** [comment]
Some preliminary results:
It turns out that at least currently, GKE will let you update a cluster to a supported version as outlined [here](https://cloud.google.com/container-engine/release-notes), but initial cluster up can be created only with version 1.5.6, as of right now. This is true for both k2 and ```gcloud container clusters create```.
K2 uses a deployment-manager instead of gcloud container clusters create, so it is *not* possible to specify the desired version with a simple flag in create-cluster.yaml.
Running cluster up again with k2 and a different version specified in the config file (this version must still be gke supported, and cannot be just any version) will trigger the nodes to be updated, a process that is currently taking about an hour, way longer than bringing up an initial cluster.
I have to finalize and verify, but it seems as though just adding a kubeConfig stanza is enough to tell the deployment-manager what to do with regards to the node version.
Side Note: for gce, the version should be specified as "1.5.6" not "v.1.5.6". It hangs up on version verification otherwise.

**Comment by guineveresaenger** [comment]
To follow up on previous comment: 
It appears no changes need to be made to k2 in order to support versioning for gke. Here are the steps needed to specify a version:
1) Add a kubeConfig stanza to the default gke config file, and reference it in the node-pools (see below). **Note:** the version for gke should be in the following format: ```version: 1.5.6```
2) upon running cluster up with k2, gcloud's deployment manager will pick up on the specified version, and attempt to spin up a cluster with that version.
3) GKE currently only supports version 1.5.6 for initial cluster up, so that must be the initial version, otherwise the cluster up will fail, unfortunately. This may change according to gke's whim, of course, so perhaps add a comment in the config file to look up the currently supported version before attempting to run a cluster up?
4) To change kubelet version in the nodes, alter the version in the config file (making sure to use only ones allowed by gke), and run cluster up again. This will update the nodes, and will take about an hour.
5) Shiny new k8s version in all the nodes!

**Comment by guineveresaenger** [comment]
Here's @yenicapotediaz' PR: https://github.com/samsung-cnct/k2/pull/314

**Comment by guineveresaenger** [comment]
And here's my PR for kraken-ci-jobs: https://github.com/samsung-cnct/kraken-ci-jobs/pull/168

**Comment by coffeepac** [comment]
Both PRs merged.  Looks good.
