### ISSUE TITLE
Kubernetes System Logging in K2

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#478]
This is the parent ticket for finalizing our logging system.  The output of this ticket should be:
- a final design of our logging system 
  - should include two options, one with kafka one without
  - include all data sources currently not included
  - fluentbit on the node (may be slightly trickier with the lack of fluentd plugins)
- a set of issues to enact these changes

**Comment by coffeepac** [comment]
Data sources:
 - dmesg/journald (node level logs)
 - kubernetes system logs
 - archive events stream
 - etcd logs

**Comment by coffeepac** [comment]
the (maybe) tricky-ish part about fluentbit as the primary collector going straight to ES is how to demonstrate a custom plugin that will send an message to an external system that isn't ES.  I say this having not studied the fluentbit architecture so I don't know if it supports fanout natively or if that's something we can hack in

**Comment by DStorck** [comment]
We need to come up with a system to house the charts and image for the logging work.  There has been talk of doing it like Zonar did, but we should have a CNCT strategy for this organization. The current conflict that has been bugging me is that the image referenced [here](https://github.com/samsung-cnct/k2-charts/blob/master/elasticsearch/values.yaml) is built from a Dockerfile [here](https://github.com/samsung-cnct/elasticsearch-kubernetes/blob/master/init/Dockerfile), but there is no trigger to push the image to quay, and therefore changes do not get registered.  These things are related and should live together.

**Comment by DStorck** [comment]
Quick reminder that the parts of the logging system that run on all nodes may need to include some tolerations in order to run on master nodes.

**Comment by coffeepac** [comment]
we may want to do a neat thing which is not develop the 'logging system light' in-house but to do it in the kubernetes community.  I am, technically, the owner of that project so putting our work into the community helps everybody

**Comment by jandrake** [comment]
Some things to consider:

- Does this need multi-tenant support? As an example, and this is to expand thinking around this not requirements as of yet, Arun @ Zonar is interested in whether or not he can use our logging pipeline instead of building his own.

- How do we find and access archived data?

- Will the design support multiple log formats.  Fluentd supports JSON mostly; however, other formats

- What is the first use case for the logging system?  For accessing the data provided by the logging system?  Let's have at least one to start with.

- Will the design require logging clients to store and forward in the case of system unavailability?

**Comment by jandrake** [comment]
Please note that Prometheus seems to have a significant achilles heel failure mode in terms of a failure of network connectivity and an inability to request back data from reporting nodes.  The prometheus clients are not required, it seems to store and forward.  This means that a node or container that can't be reached will have missing data - the impact being: potentially no retro inspection of the entity should it experience problems that either led to the network connectivity problem or happened during the network connectivity problem.

**Comment by leahnp** [comment]
@coffeepac can you clarify this bullet point: fluentbit on the node (may be slightly trickier with the lack of fluentd plugins)

**Comment by leahnp** [comment]
@jandrake - some answers and some more questions for your points of consideration:

_Does this need multi-tenant support? As an example, and this is to expand thinking around this not requirements as of yet, Arun @ Zonar is interested in whether or not he can use our logging pipeline instead of building his own._ I don't think I fully understand what you mean by "multi-tenant" but our vision for logging is that we will have two maintained Helm charts - one for "central logging" (heavy) and one for "logging light". Since they are open source anyone wanting to deploy a logging solution in their K8s cluster and deploy with one Helm chart install. 

_How do we find and access archived data?_ Good question, I am still looking into what long term storage product is best for this and I will make a note to integrate some type of visualization method for data older than what is available in the elasticsearch/kibana component.

_Will the design support multiple log formats. Fluentd supports JSON mostly; however, other formats._ This seems like a good idea - can you give me some examples of other formats I should consider a priority?

_What is the first use case for the logging system? For accessing the data provided by the logging system? Let's have at least one to start with._ Does Patrick's second comment on this issue answer this question? I would like a concise answer to this also, so let me know if outlining the data sources we are pulling logs from is what you are looking for. 

_Will the design require logging clients to store and forward in the case of system unavailability?_ Yes, components responsible for forwarding data also have a buffering feature to hold onto data in the event that networks or other logging components are unavailable - BUT on this topic, it would be cool to know the breaking points of what each component can buffer, something like "if your network is down for X amount of time, Fluentd will fail".

**Comment by leahnp** [comment]
Spent today looking into K8s changes since our last design (CRI mostly: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/container-runtime-interface-v1.md), deploying the current k8s logging solution, the fluentd image 1.24 did not work for me (rolled back to 1.22) and note: nodeSelector: beta.kubernetes.io/fluentd-ds-ready: "true" necessary for daemonset to create pods.

**Comment by coffeepac** [comment]
@leahnp re fluentbit: if we need to do any on-node processing to format logs correctly (add metadata, record building), if we need to read from something other than a file (journald, syslog, etc).  I haven't taken a look at fluentbit's plugins lately so maybe this is less of a thing now that the golang plugin API.

**Comment by leahnp** [comment]
Need to decide between Fluent-bit and FluentD for daemon on-node collector. Fluent-Bit 10x smaller, seems to have all the input/output/filters we need, but we may have to contribute some fixes (newer/developing technology). Currently I am testing all the plugins we need.

**Comment by DStorck** [comment]
* When tickets get made for work on this - please include a small ticket to update statefulSets to apps/v1beta1

**Comment by leahnp** [comment]
I am still working out some details, but I wanted to get the core design up for consideration. 

Diagram: https://www.gliffy.com/go/share/sq3yrt6yg93hwbfekqnm
Implementation details: https://docs.google.com/document/d/18id3iJeyDH5P4cIk-pZEuPi_xr_Kp14W27uur6E6Qqo/edit?usp=sharing

**Comment by leahnp** [comment]
And the design proposal for logging-lite: https://docs.google.com/document/d/1f87_w24qu15tn1Gl8EJLU9Mrue1GU-NFrE9Ia0Iqrok/edit

**Comment by leahnp** [comment]
Proposals PR: https://github.com/samsung-cnct/docs/pull/15/files

**Comment by leahnp** [comment]
Issues to implement design:

Fluent-bit:
https://github.com/samsung-cnct/k2-logging-fluent-bit-daemonset/issues/8
https://github.com/samsung-cnct/k2-logging-fluent-bit-daemonset/issues/9
https://github.com/samsung-cnct/k2-logging-fluent-bit-daemonset/issues/10
https://github.com/samsung-cnct/k2-logging-fluent-bit-daemonset/issues/11
https://github.com/samsung-cnct/k2-logging-fluent-bit-daemonset/issues/12

Kafka output plugin:
https://github.com/samsung-cnct/fluent-bit-kafka-output-plugin/issues/5

Kafka:
https://github.com/samsung-cnct/kafka-kubernetes/issues/5
https://github.com/samsung-cnct/kafka-kubernetes/issues/6

FluentD:
https://github.com/samsung-cnct/k2-logging-central-fluentd/issues/4
https://github.com/samsung-cnct/k2-logging-central-fluentd/issues/5
https://github.com/samsung-cnct/k2-logging-central-fluentd/issues/6

ElasticSearch:
https://github.com/samsung-cnct/elasticsearch-kubernetes/issues/8
https://github.com/samsung-cnct/elasticsearch-kubernetes/issues/9
https://github.com/samsung-cnct/elasticsearch-kubernetes/issues/10

Kibana:
https://github.com/samsung-cnct/kibana-k2-dependencies/issues/1
https://github.com/samsung-cnct/kibana-k2-dependencies/issues/2

K2-Charts:
https://github.com/samsung-cnct/k2-charts/issues/119

K2:
https://github.com/samsung-cnct/k2/issues/698

**Comment by leahnp** [comment]
To Review: 
check issues make sense and will implement design proposal
merge design proposal

**Comment by leahnp** [comment]
@coffeepac want to close this and move it into 'done'?

**Comment by coffeepac** [comment]
@leahnp there isn't anything in this design for archiving out the stream of events in etcEvents.  I'll file a research spike as I'm pretty sure this is an area of research.
