### ISSUE TITLE
etcd node recovery process

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#559]
this is a tracking issue for building a process that allows for rebuilding a degraded etcd within a K2 install.  this process is only expected to work with automation on an etcd cluster that still has a majority of the nodes available.

there should also be a manual process specified that will support rebuilding an etcd cluster that has gone into a 'read-only' state.  

the specifics of this may mutate greatly over the life of this issue. Please work closely with @alejandroEsc and @sostheim to stay on track

**Comment by sostheim** [comment]
notes for context:
- the initial cluster configuration for this deployment has only two availability zones.  there is a great deal of information on the two AZ design here: https://github.com/samsung-cnct/cts-k8s-2017/blob/master/documents/cluster-design-specification.md
- this issue is time sensitive as we need to have a "presentable" solution for external use for July 1st (short holiday week), Wed 5th - Fri 7th.

**Comment by NathanZook** [comment]
Looking at the etcd documentation, I feel like there is some sort of mismatch or three.

First, the documentation for changing clustering configurations in etcd indicates that they are not implementing the raft methodology.  Raft changes configurations by 1) writing the proposed new configuration as a proposal, 2) bringing up the new nodes, 3) requiring leader elections until a node becomes the leader in both the old & new configuration 4) writing the new configuration as accepted.  This eliminates the concerns about wrecking a cluster when adding a misconfigured node.

Second, I don't get the presumption that the cluster is somehow configured to some fixed set of machines.  How is this done?  There is some sort of local addressing scheme that the cluster is using, and if a node fails for whatever reason, a new node is spun up that answers on the address of the failing node, and the system is designed to just work from there.

---

We mentioned some of the issues surrounding this a month ago or so.  The answer to a cluster losing nodes is to have something in place to monitor those nodes & spin up replacements.  Catastrophic failure should mean that all of the nodes are down and all of the logs are lost.  Properly implemented, I just don't see how anything less is more complicated than monitoring & restoring lost resources.

**Comment by davidewatson** [comment]
- [ ] Split etcd out into it's own role for safetly
- [ ] Document etcd assumptions and manual recovery process

**Comment by davidewatson** [comment]
There are (at least) two ways to split etcd resources out from the rest of our infrastructure. Separate top level tf files and the `-target` option.

- Separate top level tf files are not backward compatible with existing k2 because all tf files are assumed to be in `~/.kraken/clusterName`

- `-target` will work but is not ([yet](https://github.com/hashicorp/terraform/pull/9236)) recursive. This matters because the etcd module depends on the vpc, route53, and subnet modules:

```
module "etcd" {
  source = "./etcd"

  vpc_id = "${module.vpc.id}"
  etcds_name  = "{{cluster.name}}"
  cidr_block = "{{cluster.providerConfig.vpc}}"
  route53_zone_id = "${module.route53.route53_zone_id}"
{% for node in cluster.nodePools %}
{% if node.etcdConfig is defined %}
  {{node.keyPair.name}}_{{node.name}}_key = "${module.keypair.{{node.keyPair.name}}_keyname}"
{% endif %}
{% endfor %}  
  
{% for node in cluster.nodePools %}
{% if node.etcdConfig is defined %}
{% for subnet in node.nodeConfig.providerConfig.subnet %}
  {{subnet}}_{{node.name}}_subnet_id = "${module.subnet.{{subnet}}_subnet_id}"
{% endfor %}
{% endif %}
{% endfor %} 
} 
```

**Comment by coffeepac** [comment]
from @sostheim: hard deadline is for Friday the 28th

**Comment by coffeepac** [comment]
closed by samsung-cnct/issues#
