### ISSUE TITLE
etcd readiness check

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#561]
we should have a readiness check for any etcd clusters that causes creation of master nodePool resources to wait until the etcd clusters are up and running.  this should prevent errors where our etcd clusters are coming up a bit wedged.

**Comment by davidewatson** [comment]
We have to be able to check etcd cluster health before k8s is available. This should be doable using the external IP addresses assigned to each etcd node. We have a choice though. Should we use `ssh` to login to the node and run `etcdctl` against loopback, or do we think it's okay to use the external endpoint and port? I am going to prefer loopback since then we can tighten our firewall rules to prevent nodes external to the cluster from connecting to the etcd cluster.

+ @venezia for awareness

**Comment by coffeepac** [comment]
+1 to loopback.
