### ISSUE TITLE
allow user to add/delete node pools from config file and have this update a running cluster

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#576]
Use Case:  a user would like to add a new nodepool to a running cluster.  They add the nodepool to the config file, run `update` and the new nodepool is created.

Use Case:  a user would like to delete a nodepool from a running cluster.  They remove the nodepool from the config file, run `update` and the nodepool is deleted.

For both use cases, master nodepools should not be allowed to be created or deleted (detect this by checking for apiServer config key).

This may be done except for master nodepool mangling prevention.

**Comment by guineveresaenger** [comment]
Preliminary results:
- Adding a nodepool will happen automatically when running update. The only issue with this is that the update action fails if no nodepools were passed. So the new nodepool will quietly get added whilst running update on a _different_ nodepool. I am not sure what happens if you explicitly pass the new nodepool. 
- Next steps: see if a nodepool can be removed .
- I believe it is possible currently to add master nodepools, although why somebody would want to do so is puzzling. There is definitely some work to be done there.

**Comment by guineveresaenger** [comment]
It turns out nodepools can and will be removed, due to the up action being included in the cluster.
If the nodepool-to-be-removed was passed as an argument to the update command, it will still fail awkwardly:
`TASK [/kraken/ansible/roles/kraken.update/kraken.update.aws : Fail when nodepools passed do not exist] **************************************
failed: [localhost] (item=extraSpecialNodes) => {"failed": true, "item": "extraSpecialNodes", "msg": "You passed a nodepool that does not exist in this cluster. Please make sure to pass --nodepools <comma,separated,list,of,nodepools> to update action."}`

Summary:

The basic functionality for adding and deleting nodepools is there; I recommend some explicit documentation and also perhaps tweaking error/status messages a bit to better reflect that nodepools could have also been added or deleted. But, given that adding and deleting nodepools does not need to trigger the cordon/drain/terminate/regenerate process, this is mostly good to use as is, with the exception that one should not be able to add or remove master nodepools.

**Comment by coffeepac** [comment]
@joejulian is this a feature you need right nowish?

**Comment by joejulian** [comment]
Thanks, @guineveresaenger. 
@coffeepac: It is, yes.

**Comment by coffeepac** [comment]
@guineveresaenger can you get started on this then?  I'll put it on the board.

**Comment by guineveresaenger** [comment]
@joejulian @coffeepac - to clarify:
- we want to add a check that prevents master nodepools from being added or deleted? Or do we want to handle that with explicit documentation for now? The only issue I'm having is that adding/deleting nodepools via config file is not an explicit feature of the update task --- it happens during the up tasks. So I'll have to do some digging.
- also add to the README a section for "Adding and Deleting Nodepools"
- currently, the playbook fails when no nodepools were passed to update action. We can alter this behavior and not fail and instead use it to set a flag to either run the individual node upgrades or not; the downside is that in case the user meant to pass nodepools to update, they will not get a helpful error.

@joe let me know your thoughts

**Comment by coffeepac** [comment]
it may be easiest to add a switches to `update.sh` for `add-nodepool` and `delete-nodepool`.  they would take the name of the nodepool to operate on.  I would want a check for `add-nodepool` to ensure the nodepool exists and `delete-nodepool` would check that the listed nodepool doesn't exist.  this allows the current `nodepools` flag to operate as normal.

documentation is sufficient for not adding multiple master nodepools or deleteing a nodepool.  

and when we have config backups being taken we can do more interesting validations, especially for `delete-nodepool`.

**Comment by guineveresaenger** [comment]
PR: #600
