### ISSUE TITLE
Support k8s 1.7.x

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#607]
k8s v.1.7.0 ([CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v170)) has been released. k2 needs to be updated to support 1.7.x and 1.4.x support should be removed. k2-tools will also need to be updated.

**Comment by davidewatson** [comment]
RBAC changes will be needed for any resources using API version: `rbac.authorization.k8s.io/v1alpha1` In particular, the fabric daemonsets are affected.

@DStorck: New in 1.7, "The DaemonSet controller will evict running Pods that do not tolerate the NoSchedule taint if the taint is added to a Node." FYI

**Comment by alejandroEsc** [comment]
Ill help with the fabrics side of this ticket if its ok with everyone?

**Comment by coffeepac** [comment]
we need to do this nowish.  I will up the priority level and drag to ToDo after a discussion in Post.

**Comment by davidewatson** [comment]
From slack: "helm doesn't work with 1.7 stateful sets"...

**Comment by mikeln** [comment]
RBAC: system:node is deprated (which is used by kubelet).   https://kubernetes.io/docs/admin/admission-controllers/#noderestriction   is the recommendation.

**Comment by coffeepac** [comment]
note: GKE supports 1.7 but the default is still 1.6.4 so leave that until this page: https://cloud.google.com/container-engine/release-notes updates (will be caught during weekly version check most likely)

**Comment by samba** [comment]
A few findings in my work on this so far...

- [Helm support for 1.7 is expected in Helm's 2.6.0][1]
- In generating the `admin.kubeconfig`, we're adopting the username `admin` from the basic auth components, but the `{{ cluster.name }}_admin` is configured as the super user for RBAC. This prevents the cluster from spinning up because the user `admin` cannot query nodes, etc. *I have a fix for this already pending.*
- Currently getting a lot of `FailedSync` status from kubelet when attempting to deploy services (without helm) on 1.7... investigating.

Given our current reliance Helm, I'd guess that we shouldn't expect to merge support for 1.7 into K2 until Helm's 2.6.0 is available; correct? Thoughts?

[1]: https://github.com/kubernetes/helm/releases

**Comment by mikeln** [comment]
Just remembered,  the DNS services are setup with specifc template directories.  unknown version default to the 1.4 setup.   Need to copy the v1.6 template dir to v1.7, and update the defaults/main.yaml for 1.7 versions.

**Comment by mikeln** [comment]
Also noticed that the kraken.fabric/ flannel  will also default to pre-v1.6 setup...which probably won't work in 1.7   need to create v1.4,v1.5 subdirs and copy the 3 files into them.  leave namespace.  then copy the v1.6 files up a level, but leave the v1.6 subdir.   This way 1.7 will use the copy of the v1.6 files as default.  (vs the pre-1.6 files).

**Comment by coffeepac** [comment]
don't need to do anything for v1.4 as part of supporting v1.7.  once we get v1.7 working we will be dropping v1.4

**Comment by samba** [comment]
@coffeepac @mikeln are we at a good point to call this "done" since the other work was merged?

**Comment by coffeepac** [comment]
there are a few issues that are rattling around but this work is done.
