### ISSUE TITLE
Increase etcd and etcdEvents AWS Machines to t2.medium

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#670]
The split of etcd startup has shown many unsuccessful etcd cluster startups.
An initial thought was to try increasing the AWS machine size.  This seems to have greatly improved the startup reliability.

Recommend changing from t2.small to t2.medium for etcd and etcdEvent.

**Comment by coffeepac** [comment]
Sounds good to me.

**Comment by alejandroEsc** [comment]
@mikeln what makes you believe it is a sizing problem? Last night i have tried to stand up a cluster using m4.large for etcd(events) and in all cases one or the other clusters have failed. Also why arent we using etcd recommendation on sizing from k8s: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/hardware.md#example-hardware-configurations

Finally, is the resolution here some documentation with a config change only?

**Comment by mikeln** [comment]
Please add any error information here: #673

**Comment by mikeln** [comment]
Just a hunch on the sizing issue, based on past experience with other pieces of kubernetes.  Probably isn't be be-all/end-all fix, but it took my cluster start ups from 70% failed startups from etcd, to 20%.   

That sizing reference is great!...however, it looks like it assumes a single etcd server, vs a cluster(?)...
I think we assume a cluster would not required such large machines, since we distribute the workload.  So we want the smallest (cheapest) set of machines that will do the job.

Also, note.. I am not the etcd sizing expert at all.  Just reporting what seemed to help.

**Comment by mikeln** [comment]
Also, the fix has to be put into our default config.yaml files since that is what CI uses.   A recommended config change in a doc wouldn't help our CI reliability :)

**Comment by mikeln** [comment]
hmm... maybe update etcd to 3.2.4?  also seems to work faster.

**Comment by mikeln** [comment]
same issues, but so far only seeing 1 out of 5 nodes fail.  Sometimes recover quickly though.
Other times, still spinning with raft errors.

**Comment by mikeln** [comment]
Let it run for a long time, etcdEvents-5 never synced up.
Did a `systemctl restart kraken-etcd.service` now it runs and fails, restarts  continuously.

**Comment by mikeln** [comment]
ok, upping to etcd 3.2.4 .. just validated that t2.small just doesn't work for that ...

**Comment by davidewatson** [comment]
Fully agree with increasing the default etcd instance size to either t2.medium or t2.large. The sizing [documentation](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/hardware.md) from CoreOS suggest between 2 and 4 vCPUs per node. This corresponds to either a t2.medium or a t2.large. SInce they also recommend 8 GB RAM, this means a t2.large.

Note that while I understand that steady state etcd performance may not (usually) be CPU bound, I would be even more comfortable for a prod deployment to avoid the burstable instance types altogether and use m4.xlarge (4 vCPUs, 16 GB RAM), however, for defaults, it might makes sense to be more cost sensitive.

Finally, since we plan to combine etcd and etcdEvents on the same instances in the future (cf. https://github.com/samsung-cnct/k2/issues/620), we may need to increase the instance size even further, even for moderately sized clusters.

Patch to follow.
