### ISSUE TITLE
Process Improvements Needed for a Bigger Group

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#706]
Just some thoughts on helping ease/distribute the workload of our group.

Issues:

1) Our issue/PR velocity is very slow due to CI runs taking too much time, failing on flakes, failing on bad cluster start.  Anything we can do to help that, I think helps us exponentially.   
    a) More reliable cluster starts
    b) Faster cluster starts
    c) Filter the needed CI testing down to what is needed...vs everything always

2) Keeping up with the innudation of issues/PRs is hard via github itself.  A separate tool to help filter the worklaod for each person would be good ( I triage github notifications through email…which helps, but still can be too much).

3) Speaking to that also, time spent checking github notifications to determine if an issue/PR is something I really need to be participating in takes more time.  While I think we all should know the whole system…it is becoming impractical to continually do that.  This is where I think the CODEOWNERS file in github would help.

**Comment by mikeln** [comment]
2)  that’s basically a subset of gubernator
https://k8s-gubernator.appspot.com/pr/thockin

**Comment by mikeln** [comment]
Another idea, do not block on e2e conformance failures in CI for dev_integ, but make sure the run has some indication that conformance failed.  Then have a "release" or prod CI pipeline that does block on e2e conformance failures.   

So, this suggestion is based on the fact that kraken currently hasn't failed conformance for anything we've done.   It fails due to test flakes and timeouts.   Blocking CI approval because of these failures really slows down our PR velocity.   However we do want a clean conformance stamp on released versions.

**Comment by coffeepac** [comment]
1. @davidewatson is working on etcd reliability.  should be done by end of week.  While this will help with 'a' it will harm 'b'.  We can work on 'b' after 'b' is done.  For 'c' I could be convinced to skip e2e for PRs and only have it for stable k2 releases.

3. is being handled here:  https://github.com/samsung-cnct/k2/pull/720

**Comment by coffeepac** [comment]
number 2?  https://github.com/pulls/review-requested

**Comment by coffeepac** [comment]
To Review:
the following items sufficiently address this issue for now
- reasonable progress has been made and issues are filed to handle CI velocity
  - CI for PRs is a warning if e2e failed
  - issue open for etcd reliability (#673)
  - issue open for control plane startup (#701)
- https://github.com/pulls/assigned seems a good github native tool for managing PRs each contributor needs to manage
- #720 added a CODEOWNERS file, a CONTRIBUTORS.md and a SUPPORT.md

if additional items are desired please either add them as requirements to this issue or create a new issue.

**Comment by leahnp** [comment]
CI looks good.

To sum up the new process (please correct me if I'm wrong):

- all PRs need 2 assigned reviewers
- If you are named as a 'codeowner' you are responsible for closely monitoring PR's and conversations on that code
- new repos/projects must include the team's standard `CODEOWNERS file, a CONTRIBUTORS.md and a SUPPORT.md` files

**Comment by coffeepac** [comment]
I would say, in order:
- all PRs need 1 assigned reviewer.  if the assigned reviewer isn't comfortable making the decision they should bring someone else in
- yes, all of use should start using https://github.com/pulls/assigned  to track PRs that are assigned to us
- new repos/projects should include these files.  I say 'should' because as of right now there are no standard files.  Instead I would say all new repos/project must include some version of these files.  I have opened samsung-cnct/issues#43 to handle creating a backstop group so there aren't PRs going unassigned.

**Comment by leahnp** [comment]
LGTM

**Comment by oneilcin** [comment]
How are labels used in issues.  In Jira you have the concept of Epics, Stories and Tasks.  How do we track these things.  Should we be using a tool like Jira?

**Comment by coffeepac** [comment]
labels are for a couple of tasks:
- how important ( @leahnp covered this in chat, p0, etc)
- type of issue (bug, feature request, research spike)
- project ( K2, k2cli, etc, this is the same for every issue in a given repo, it might help with the project board, I'm not certain)
- optionally a larger project thread (CI, logging, multi-cluster, etc).  This is optional because not all issues will have a larger project.

We are going to continue to use github for all project management work until it shows that it can't handle the load.  I will also be writing up something more formal for this and sending a PR hopefully today.
